name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  DOTNET_VERSION: '9.0.x'

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore --configuration Release
    
    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal
    
    - name: Copy template files
      run: |
        cd templates/MyCustomAnalyzer
        cp TemplateAnalyzer.fs TestAnalyzer.fs
        cp TemplateAnalyzerTests.fs TestAnalyzerTests.fs
    
    - name: Add template files to project
      run: |
        cd templates/MyCustomAnalyzer
        # Add compile items to the empty ItemGroup
        awk '
        /<!-- DO NOT include TemplateAnalyzer.fs or TemplateAnalyzerTests.fs - they are template files only -->/ {
          print $0
          print "    <Compile Include=\"TestAnalyzer.fs\" />"
          print "    <Compile Include=\"TestAnalyzerTests.fs\" />"
          next
        }
        { print }
        ' MyCustomAnalyzer.fsproj > temp.fsproj
        rm MyCustomAnalyzer.fsproj
        mv temp.fsproj MyCustomAnalyzer.fsproj
    
    - name: Build template project
      run: |
        cd templates/MyCustomAnalyzer
        dotnet build --configuration Release